### ISSUE TITLE
Switch between node version and PATH (also show node and npm versions & PATHs in use)

### ISSUE THREAD

**Issue by AddictArts** [720kb/ndm#143]
#### REQUIRED 
OS / OS version: Mac OS El Cap 10.11.6

ndm version: 0.1.4
 
node version: 7.4

npm version: 4.1.2

node installed via (brew, n, nvm, pkg, other ...): brew and nvm

#### OPTIONAL 

$ which node: /usr/local/nvm/versions/node/v6.2.2/bin/node

$ which npm: /usr/local/nvm/versions/node/v6.2.2/bin/npm

#### IMPORTANT

- npm permissions fixed or not-fixed? (see https://docs.npmjs.com/getting-started/fixing-npm-permissions):

- If you are using npm > v4.1.1 then run `npm doctor` and paste the output here:

#### APPRECIATED
_open the devtools console: OS Menu -> View -> Developer -> Open DevTools_

Now make a screenshot of your devtools console or paste the devtools console full-log in here:

#### THE PROBLEM
What's the problem you facing,  in few lines:

There is no way to know which nodejs and npm nam is using. I believe it is using the system, but how does  it pick and ideally you could edit or pick the nodejs and npm path.

#### REPRODUCE THE PROBLEM
How to reproduce the problem in few lines:

**Comment by 45kb** [comment]
@AddictArts Hi, thanks for the suggestion.

Actually, this is how https://github.com/720kb/ndm/blob/master/lib/js/npm/npm-api.js#L183 your PATH is imported into the app, so you can change anything by your own and the app will inherit that (hopefully 🙏 )

The two infos (node -v) and (npm -v) will be shown in the app footer sooner, this is something i thought to do time ago but never got the time sincerely.

Pick installation is not something i would demand to a third parties app since nodejs (and so npm) got many simple tools to handle the installation.

I mean when it comes to install node via nvm or brew it's seriously 1 command in the terminal, and to switch node version it's 2 commands.

I believe the node installation and update is something you going to do 1 time per month  more or less, and imho it doesn't worth the headache.

However let's take this thread open so others can share their thoughts about this.


Also some more feedbacks and suggestions would be appreciated @people

**Comment by AddictArts** [comment]
Thanks @45kb 

Let me clarify. I don't want it to help with installation or be a tool for installation. What would be nice is as you mentioned, show the versions. It would also be nice if you could pick from installed versions, ones you installed with nvm or brew. For example through a settings ui.

I see that it uses the my PATH, but at first I didn't know which node version it was using from the many I have installed. That led me to creating this issue. Thanks again.

**Comment by 45kb** [comment]
@AddictArts Oh i am sorry i did misunderstand so, my bad.

I'm gonna change the issue title, personally i like the settings idea, which would be useful for many other stuff in the yard :)

The only thing i wonder is why would you pick a different node or npm PATH or version?

Asking this because is not something i do usually, i just install the version i want and just use it.

**Comment by AddictArts** [comment]
I've had occasion where an old project could not be updated to the latest nodejs. I also have npm packages that don't work with newer versions of nodejs. So, I switch often between nodejs versions.

**Comment by 45kb** [comment]
@AddictArts clear ... actually have you tried ndm with all the projects you says (old and new projects)? Is it working?

The app does not make use  of the npm you have installed on your machine. 
We use npm.js inside the app so npm version should be not really a problem.

As for node versioning is not something we are going to handle since the app has one only aim and it's to handle npm and packages.

I think a good option would be to embed a js terminal console inside the app so that for any command you have to run outside of npm you don't have to move outside of the app...  let's say you want to change the node version just open the console and run what you need to run.... !?

That way you really don't have to move out of the app for any little thing...

@wouldgo what you think?

**Comment by AddictArts** [comment]
@45kb ndm works fine for each project if I have a terminal open and do the nvm incantation to switch node versions. Then restart the ndm app. Note this only relates to Globals which is not really a crucial need. No errors, so thanks for asking.

I didn't understand when running ndm at first that it used npm.js, so I was not sure which node/npm on my system it found. I like the terminal idea and understand how settings might not be enough.

For me at least identifying where the Globals is, path, would be nice. I don't mind switching with nvm and re-running ndm. Thanks for the feedback.

**Comment by 45kb** [comment]
@AddictArts thank you too for sharing your thoughts and suggestions with us.

We should not forget that  nvm is not the only one ... people use nvm, n, brew and probably even others, so that will be out of scope for ndm really...

However as soon as we can focus on this some idea will comes up!

For the moment just be sure to keep ndm app up to date so you get any new feature on the fly ;)

**Comment by 45kb** [comment]
closing in favor of: https://github.com/720kb/ndm/issues/173
