### ISSUE TITLE
Windows version ?

### ISSUE THREAD

**Issue by tebeco** [720kb/ndm#51]
* OS: Windows
* OS version: Windows 7 SP1 / Windows 10
* Node version: 5.x, 6.x, 7.x
* Npm version: 3.10.x
* Node installed via : MSI Installer

Is there a future view of this tools compliant for Windows too since it's designed in JS / Html ?

**Comment by 45kb** [comment]
@tebeco this will be later  see FAQ section https://github.com/720kb/ndm#faq

> Why Mac only?
> 
> We now focus on one OS but the app is developed keeping in mind that it will have to run also on other OSs. We won't put too much meat on bbq for the moment, it is now very important to obtain an OS-abstracted and stable app.
> 
> As soon as we are sure that the project is stable, it will be delivered to the other OSs.

**Comment by tebeco** [comment]
Thx i did not see this mention

Hope it will be less painfull to make it cross platform after dev is done than make it cross platform with a "fake JS / Html page" and then implement around ;)

**Comment by ahallicks** [comment]
I have downloaded and played with the app (v0.0.6beta) on Windows and it generally works really well. I can add projects, updated packages and run *some* scripts.

I copied the Mac styles so it looks like a Mac app, but I don't think it will actually be too much work to get this working mostly on Windows.

**Comment by 45kb** [comment]
@ahallicks hey! thanks for feedback, appreciated a lot!!

Technically, the app is a wrapper over `require('npm')` and since npm.js is a wrapper for npmCLI (which is cross-platform) then the app (specially thanks to Electron) is supposed to be cross-platform too...

We would like to finish: 1 - autoupdates, 2 - SCSS for linux and windows. 

SCSS and GUI in general is not a problem, the only problem is that i am not so good at tasks, tests, autoupdates... :D  
@wouldgo is the man who practically setted up everything the app needs, but atm he is very busy.
Any help would be so much appreciated, really.
