### ISSUE TITLE
.AppImage "npm not installed"

### ISSUE THREAD

**Issue by probonopd** [720kb/ndm#89]
Run ubuntu-16.04-desktop-amd64.iso, launch ndm-0.1.0-x86_64.AppImage. Says "You have not installed npm on your machine. Relaunch ndm as you have installed it."

* OS: Ubuntu
* OS version: ubuntu-16.04-desktop-amd64.iso
* Ndm version: None installed on host, would expect it to come inside ndm-0.1.0-x86_64.AppImage
* Node version: None installed on host, would expect it to come inside ndm-0.1.0-x86_64.AppImage
* Npm version: None installed on host, would expect it to come inside ndm-0.1.0-x86_64.AppImage
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions):
* Node installed via (brew, n, nvm, pkg, other ...): ndm-0.1.0-x86_64.AppImage
* How to replicate the bug/issue, if you know: Run ubuntu-16.04-desktop-amd64.iso, launch ndm-0.1.0-x86_64.AppImage. An AppImage is supposed to have no dependencies other than the target system (e.g., ubuntu-16.04-desktop-amd64.iso). Hence, NodeJS and npm should come bundled inside the AppImage.

**Comment by 45kb** [comment]
@probonopd thanks for reporting this, could you be so gentle to send a screenshot of the app devtools console (OS menu -> View -> developer -> open devtools) if possible

**Comment by probonopd** [comment]
![screenshot from 2016-12-30 01-52-36](https://cloud.githubusercontent.com/assets/2480569/21557883/b41907d8-ce32-11e6-82c3-513deb782cb4.png)

**Comment by 45kb** [comment]
@probonopd thanks! 
Do you have node and npm on your machine? 
How you installed it? 
What `npm -v` prints from the terminal? 
Does the .deb or .rpm produce the same error on your side?

**Comment by wouldgo** [comment]
Hi @probonopd,

Thanks for being interested in this project and actually we didn't know exactly how `.AppImage`es work.

After reading well [this wiki](https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages) post we undestrand that actually, with the goal that we discussed to reach for this application, atm creating an AppImage is outside our scope. We started from CakeBrew and we, as a first iteration, use shell commands directly to operate with npm; then we wrap directly the npm node library.

Those commands anyway are inevitable to be runned by shell due to the highest variety of ways to install node.js + npm.

After this we will remove the deploy of .AppImages on the build process.

Have a great day,
Dario
